services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_KEY
        sync: false
